---
preBuildScript: |
  sed -i -e "s/^def versionName = '1.5'$/group = 'com.google.re2j'\nversion = '1.6'/;" -e "s/version versionName/version project.version/;" -e "s/versionName/version/g;" build.gradle
