---
allowedDifferences:
- \Q-:narayana-jta-jakarta-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:narayana-jta-jakarta-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jts-idlj-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:narayana-jts-idlj-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jts-idlj-5.13.0.Final.jar:class:com/arjuna/ats/jts/services/transactionserver/TransactionServerService\E
- \Q-:narayana-jts-idlj-jakarta-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:narayana-jts-idlj-jakarta-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jts-idlj-jakarta-5.13.0.Final.jar:class:com/arjuna/ats/jts/services/transactionserver/TransactionServerService\E
- \Q-:arjunacore-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:arjunacore-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:arjuna-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:arjuna-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jta-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:narayana-jta-5.13.0.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jts-idlj-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:narayana-jts-idlj-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jts-idlj-7.0.1.Final.jar:class:com/arjuna/ats/jts/services/transactionserver/TransactionServerService\E
- \Q-:arjuna-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:arjuna-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:arjunacore-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:arjunacore-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
- \Q-:narayana-jta-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfGraph\E
- \Q-:narayana-jta-7.0.1.Final.jar:class:com/arjuna/ats/arjuna/tools/stats/TxPerfPlugin\E
