---
repositories:
  - "spring-plugins-milestone"
additionalArgs:
  - "-x"
  - "checkSigningRequirements"
preBuildScript: |
  sed -i /options.addStringOption/d build.gradle
  sed -i /.*propdeps.*/d build.gradle
  [[ -f project.gradle ]] && sed -i -e 's/provided/compileOnly/' project.gradle
  [[ -f build.gradle ]] && sed -i -e 's/provided/compileOnly/' build.gradle
