---
additionalMemory: 6144
javaVersion: "11"
preBuildScript: |
    export JDK_16=/lib/jvm/java-1.8.0
    export JDK_17=/lib/jvm/java-1.8.0
    export JDK_18=/lib/jvm/java-1.8.0
    export JDK_9=/lib/jvm/java-11
    export DISABLE_JBS_REPOSITORY_PLUGIN=true
repositories:
  - "all"
  - "intellij-releases"
  - "intellij-dependencies"
additionalArgs:
  - "-Pkotlin.build.isObsoleteJdkOverrideEnabled=true"
  - "-Pmaven.repository.mirror=$(CACHE_URL)"
  - "-PdeployVersion=$(params.PROJECT_VERSION)"
postBuildScript: |
  mvn -DnewVersion=$(params.PROJECT_VERSION) -DgenerateBackupPoms=false -DprocessAllModules=true -f libraries/pom.xml versions:set
  mvn -V -B -e -s $(workspaces.build-settings.path)/settings.xml -DaltDeploymentRepository=local::file:$(workspaces.source.path)/artifacts -DskipTests -DuseJBSDeployed -f libraries/pom.xml package org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy
